# Create a GitHub action to email a report from a file at 6 a.m. daily:
name: Deploy App

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Email report
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        subject: Report
        body: 'Please see the attached report.'
        to: ${{ secrets.TO_EMAIL }}
        attachments: 'path/to/report.txt'